/**
 * Help Dialog Styles
 *
 * Shared styles for HelpDialog and its sub-components.
 */

import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  dialog: {
    backgroundColor: '#252526',
    borderRadius: '8px',
    width: '90vw',
    maxWidth: '1200px',
    height: '80vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 4px 24px rgba(0, 0, 0, 0.5)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderBottom: '1px solid #3c3c3c',
  },
  title: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 500,
    color: '#fff',
  },
  closeButton: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    color: '#888',
    cursor: 'pointer',
    padding: '0 8px',
  },
  body: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  sidebar: {
    width: '280px',
    borderRight: '1px solid #3c3c3c',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  searchContainer: {
    padding: '12px',
    borderBottom: '1px solid #3c3c3c',
  },
  searchInput: {
    width: '100%',
    padding: '8px 12px',
    backgroundColor: '#1e1e1e',
    border: '1px solid #3c3c3c',
    borderRadius: '4px',
    color: '#fff',
    fontSize: '14px',
    outline: 'none',
  },
  topicList: {
    flex: 1,
    overflow: 'auto',
    padding: '8px 0',
  },
  category: {
    marginBottom: '8px',
  },
  categoryLabel: {
    padding: '8px 16px 4px',
    fontSize: '11px',
    fontWeight: 600,
    color: '#888',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  topicButton: {
    display: 'block',
    width: '100%',
    padding: '8px 16px',
    backgroundColor: 'transparent',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    color: '#ccc',
    fontSize: '13px',
  },
  topicButtonActive: {
    backgroundColor: '#37373d',
    color: '#fff',
  },
  topicTitle: {
    display: 'block',
  },
  groupContainer: {
    marginTop: '4px',
  },
  groupHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    width: '100%',
    padding: '6px 16px',
    backgroundColor: 'transparent',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    color: '#aaa',
    fontSize: '12px',
    fontWeight: 500,
  },
  groupChevron: {
    fontSize: '8px',
    width: '10px',
  },
  groupCount: {
    color: '#666',
    fontSize: '11px',
    marginLeft: 'auto',
  },
  groupTopics: {
    marginLeft: '8px',
    borderLeft: '1px solid #3c3c3c',
  },
  groupedTopicButton: {
    paddingLeft: '24px',
    fontSize: '12px',
  },
  subsectionList: {
    marginLeft: '16px',
    borderLeft: '1px solid #3c3c3c',
    paddingLeft: '8px',
    marginTop: '2px',
    marginBottom: '4px',
  },
  subsectionButton: {
    display: 'block',
    width: '100%',
    padding: '4px 8px',
    backgroundColor: 'transparent',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    color: '#888',
    fontSize: '11px',
  },
  groupedSubsectionButton: {
    paddingLeft: '16px',
  },
  groupHeaderActive: {
    backgroundColor: '#37373d',
    color: '#fff',
  },
  h2Button: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    width: '100%',
    padding: '6px 16px',
    backgroundColor: 'transparent',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    color: '#ccc',
    fontSize: '12px',
  },
  h2ButtonNested: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    width: '100%',
    padding: '4px 8px',
    backgroundColor: 'transparent',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    color: '#aaa',
    fontSize: '11px',
  },
  h2Chevron: {
    fontSize: '8px',
    width: '10px',
  },
  h3List: {
    marginLeft: '20px',
    borderLeft: '1px solid #3c3c3c',
  },
  h3ListNested: {
    marginLeft: '16px',
    borderLeft: '1px solid #3c3c3c',
  },
  h3Button: {
    display: 'block',
    width: '100%',
    padding: '4px 12px',
    backgroundColor: 'transparent',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    color: '#888',
    fontSize: '11px',
  },
  h3ButtonNested: {
    display: 'block',
    width: '100%',
    padding: '3px 10px',
    backgroundColor: 'transparent',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    color: '#777',
    fontSize: '10px',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: '24px 32px',
  },
  loading: {
    color: '#888',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: '48px',
  },
  placeholder: {
    color: '#888',
    textAlign: 'center',
    padding: '48px',
  },
  hint: {
    marginTop: '24px',
    fontSize: '13px',
  },
  kbd: {
    display: 'inline-block',
    padding: '2px 6px',
    backgroundColor: '#3c3c3c',
    borderRadius: '3px',
    fontFamily: 'monospace',
    fontSize: '12px',
  },
  markdown: {
    color: '#e0e0e0',
    lineHeight: 1.7,
    fontSize: '14px',
  },
  codeBlockWrapper: {
    position: 'relative',
    margin: '20px 0',
  },
  copyButton: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    padding: '4px 10px',
    fontSize: '11px',
    fontWeight: 500,
    backgroundColor: '#30363d',
    color: '#c9d1d9',
    border: '1px solid #484f58',
    borderRadius: '4px',
    cursor: 'pointer',
    zIndex: 10,
    transition: 'background-color 0.15s',
  },
  inlineCode: {
    backgroundColor: '#282c34',
    padding: '2px 6px',
    borderRadius: '4px',
    fontSize: '0.9em',
    fontFamily: '"SF Mono", "Fira Code", Consolas, monospace',
    color: '#e06c75',
  },
  table: {
    borderCollapse: 'collapse',
    width: '100%',
    margin: '20px 0',
    fontSize: '13px',
  },
  th: {
    backgroundColor: '#161b22',
    padding: '10px 14px',
    textAlign: 'left',
    borderBottom: '2px solid #30363d',
    fontWeight: 600,
    color: '#f0f0f0',
    fontSize: '13px',
  },
  td: {
    padding: '10px 14px',
    borderBottom: '1px solid #30363d',
    color: '#c9d1d9',
  },
  link: {
    color: '#58a6ff',
    textDecoration: 'none',
  },
};
