/**
 * TypeScript AST Builder
 *
 * ts-morph wrappers for generating TypeScript AST nodes.
 */

import { Project, SourceFile } from 'ts-morph';

/**
 * Create a new ts-morph project for code generation.
 */
export function createProject(): Project {
  return new Project({
    useInMemoryFileSystem: true,
    compilerOptions: {
      target: 99, // ESNext
      module: 99, // ESNext
      strict: true,
      esModuleInterop: true,
      declaration: true,
    },
  });
}

/**
 * Create a source file in the project.
 */
export function createSourceFile(
  project: Project,
  filePath: string,
  content?: string
): SourceFile {
  return project.createSourceFile(filePath, content ?? '');
}

/**
 * Add the generated file header comment.
 */
export function addGeneratedHeader(
  sourceFile: SourceFile,
  symbolId: string,
  generatedAt: Date
): void {
  sourceFile.insertStatements(0, [
    `/**`,
    ` * @generated`,
    ` * DO NOT EDIT - This file is auto-generated by cyrus-code`,
    ` * Source: ${symbolId}`,
    ` * Generated: ${generatedAt.toISOString()}`,
    ` */`,
    '',
  ]);
}

/**
 * Format source file with consistent style.
 */
export function formatSourceFile(sourceFile: SourceFile): string {
  sourceFile.formatText({
    indentSize: 2,
    convertTabsToSpaces: true,
    ensureNewLineAtEndOfFile: true,
  });
  return sourceFile.getFullText();
}
