/**
 * Help Domain Types
 *
 * Domain types for the manifest-driven help system.
 * These types define the core data structures used across layers.
 */

// =============================================================================
// Data Types
// =============================================================================

/**
 * Help topic category.
 */
export interface HelpCategory {
  /** Unique category identifier */
  id: string;
  /** Display label */
  label: string;
  /** Category description */
  description: string;
}

/**
 * Help topic group (collapsible section within a category).
 */
export interface HelpGroup {
  /** Unique group identifier */
  id: string;
  /** Display label */
  label: string;
  /** Category this group belongs to */
  category: string;
}

/**
 * Help topic entry in the manifest.
 */
export interface HelpTopic {
  /** Unique topic identifier (e.g., "levels", "getting-started") */
  id: string;
  /** Display title */
  title: string;
  /** Brief summary for topic listings */
  summary: string;
  /** Path to markdown file (relative to project root) */
  path: string;
  /** Category for grouping */
  category: 'concept' | 'guide' | 'architecture' | 'reference';
  /** Search keywords */
  keywords: string[];
  /** Related topic IDs (optional) */
  related?: string[];
  /** Group within category (optional, for collapsible sections) */
  group?: string;
  /** Anchor within the document to scroll to (optional, e.g., "code-details") */
  anchor?: string;
}

/**
 * C4 Architecture diagram hierarchy for navigation.
 */
export interface C4Hierarchy {
  /** L1 Context diagram topic IDs */
  L1: string[];
  /** L2 Container diagram topic IDs */
  L2: string[];
  /** L3 Component diagram topic IDs */
  L3: string[];
  /** Dynamic flow diagram topic IDs */
  Dynamic: string[];
}

/**
 * Help manifest structure (docs/help.json).
 */
export interface HelpManifest {
  /** Manifest version */
  version: string;
  /** C4 diagram hierarchy for navigation */
  c4Hierarchy?: C4Hierarchy;
  /** Available categories */
  categories: HelpCategory[];
  /** Collapsible groups within categories */
  groups?: HelpGroup[];
  /** All help topics */
  topics: HelpTopic[];
}

/**
 * Output format for topic content.
 */
export type HelpOutputFormat = 'terminal' | 'html' | 'raw';

/**
 * Search result with relevance score.
 */
export interface HelpSearchResult {
  topic: HelpTopic;
  /** Match score (higher = better match) */
  score: number;
  /** Which fields matched */
  matchedFields: ('title' | 'summary' | 'keywords')[];
}

/**
 * Document heading extracted from markdown for sidebar navigation.
 */
export interface DocumentHeading {
  /** Heading text (e.g., "Code Details") */
  title: string;
  /** URL-safe anchor slug (e.g., "code-details") */
  anchor: string;
  /** Heading level: 2 for h2, 3 for h3 */
  level: number;
}

// =============================================================================
// Heading Utilities (Pure Domain Functions)
// =============================================================================

/**
 * Convert heading text to a URL-safe anchor slug.
 * Used by both backend (heading extraction) and GUI (anchor link generation).
 *
 * "Code Details" → "code-details"
 */
export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

/**
 * Extract h2 and h3 headings from markdown content.
 *
 * Extracts h2 (##) and h3 (###) headings for hierarchical navigation.
 * h2 headings become collapsible groups, h3 headings are nested items.
 * The anchor IDs match those generated by HelpDialog's markdown renderer.
 *
 * @param markdown - Raw markdown content
 * @returns Array of headings with title, anchor, and level
 */
export function extractHeadings(markdown: string): DocumentHeading[] {
  const lines = markdown.split('\n');
  const headings: DocumentHeading[] = [];

  for (const line of lines) {
    // Match h2 (##) and h3 (###) headings
    const match = line.match(/^(#{2,3})\s+(.+)$/);
    if (match && match[1] && match[2]) {
      const level = match[1].length; // 2 for h2, 3 for h3
      const title = match[2].trim();
      const anchor = slugify(title);
      headings.push({ title, anchor, level });
    }
  }

  return headings;
}

// =============================================================================
// Repository Interface (Domain Contract)
// =============================================================================

/**
 * Interface for help content data access.
 *
 * Abstracts the loading and retrieval of help manifest data.
 * Implementations handle caching and file system access.
 */
export interface HelpRepository {
  /** Load the help manifest. */
  loadManifest(): HelpManifest;

  /** Get all help categories. */
  getCategories(): HelpCategory[];

  /** Get all help groups (collapsible sections within categories). */
  getGroups(): HelpGroup[];

  /** Get all help topics. */
  getTopics(): HelpTopic[];

  /** Get C4 architecture diagram hierarchy for navigation. */
  getC4Hierarchy(): C4Hierarchy | null;

  /** Get topics filtered by category. */
  getByCategory(categoryId: string): HelpTopic[];

  /** Get a specific topic by ID. */
  getTopic(topicId: string): HelpTopic | undefined;

  /** Get related topics for a given topic. */
  getRelatedTopics(topicId: string): HelpTopic[];

  /** Get h2 headings from a topic's markdown for sidebar navigation. */
  getTopicSubsections(topicId: string): DocumentHeading[];

  /** Read raw content of a topic file. */
  readTopicContent(topicId: string): string;

  /** Clear the manifest cache. */
  clearCache(): void;
}
