/**
 * Heading Extraction Utility
 *
 * Extracts h2/h3 headings from markdown content for sidebar navigation.
 * Uses the same slugify algorithm as HelpDialog for deterministic anchor matching.
 */

import type { DocumentHeading } from './schema.js';

/**
 * Convert heading text to a URL-safe anchor slug.
 * Used by both backend (heading extraction) and GUI (anchor link generation).
 *
 * "Code Details" → "code-details"
 */
export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

/**
 * Extract h2 and h3 headings from markdown content.
 *
 * Extracts h2 (##) and h3 (###) headings for hierarchical navigation.
 * h2 headings become collapsible groups, h3 headings are nested items.
 * The anchor IDs match those generated by HelpDialog's markdown renderer.
 *
 * @param markdown - Raw markdown content
 * @returns Array of headings with title, anchor, and level
 */
export function extractHeadings(markdown: string): DocumentHeading[] {
  const lines = markdown.split('\n');
  const headings: DocumentHeading[] = [];

  for (const line of lines) {
    // Match h2 (##) and h3 (###) headings
    const match = line.match(/^(#{2,3})\s+(.+)$/);
    if (match && match[1] && match[2]) {
      const level = match[1].length; // 2 for h2, 3 for h3
      const title = match[2].trim();
      const anchor = slugify(title);
      headings.push({ title, anchor, level });
    }
  }

  return headings;
}
